[project]
name = "lda-project"
version = "0.1.0"
dependencies = [
    "bs4>=0.0.2",
    "deep-translator>=1.11.4",
    "googletrans==4.0.0rc1",
    "matplotlib>=3.10.3",
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
    "spacy>=3.8.7",
    "wordcloud>=1.9.4",
]
